version: '3.4'

services:
  questions_server_side:
    image: onkernelpanic/docker-nginx-php8-fpm:2.1.0
    container_name: questions_server_side_application
    tty: true
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/work-directory"
    depends_on:
      - database
    networks:
      - questions_server_side_network

  database:
    image: mysql:5.7.36
    container_name: questions_server_side_database
    ports:
      - "3306:3306"
    volumes:
      - "./.mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - questions_server_side_network

  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: ${ELASTIC_HOST}
    environment:
      'discovery.type': single-node
      'xpack.security.enabled': 'true'
      'http.cors.enabled': 'true'
      'http.cors.allow-origin': 'https://app.elasticvue.com'
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    volumes:
      - "./.elastic/:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - questions_server_side_network

networks:
  questions_server_side_network:
    driver: bridge


