QuestionsServerSide\Infrastructure\Doctrine\Entity\Answer\AnswerDoctrine:
  properties:
    id:
      type: string
    text:
      type: string
    result:
      type: boolean
    position:
      type: integer
    createdAt:
      expose: true
      type: DateTime<'Y-m-d H:i:s'>
    updatedAt:
      expose: true
      type: DateTime<'Y-m-d H:i:s'>