QuestionsServerSide\Infrastructure\Doctrine\Entity\Question\QuestionDoctrine:
  properties:
    id:
      type: string
      groups: [INPUT, OUTPUT]
    answers:
      type: ArrayCollection<QuestionsServerSide\Infrastructure\Doctrine\Entity\Answer\AnswerDoctrine>
      groups: [INPUT, OUTPUT]
    topic:
      type: QuestionsServerSide\Infrastructure\Doctrine\Entity\Topic\TopicDoctrine
      groups: [INPUT, OUTPUT]
    lesson:
      type: QuestionsServerSide\Infrastructure\Doctrine\Entity\Lesson\LessonDoctrine
      groups: [INPUT, OUTPUT]
    helps:
      type: ArrayCollection<QuestionsServerSide\Infrastructure\Doctrine\Entity\Help\HelpDoctrine>
      groups: [OUTPUT]
