QuestionsServerSide\Infrastructure\Doctrine\Entity\Book\BookDoctrine:
  exclusion_policy: ALL
  properties:
    id:
      type: string
      groups: [INPUT, OUTPUT]
    lessons:
      type: ArrayCollection<QuestionsServerSide\Infrastructure\Doctrine\Entity\Lesson\LessonDoctrine>
      groups: [OUTPUT]
    topic:
      type: QuestionsServerSide\Infrastructure\Doctrine\Entity\Topic\TopicDoctrine
      groups: [OUTPUT]